spring:
  datasource:
    password: 123
  mail:
    username: ltchiengue73@gmail.com
    password: "aiwf bqvt xrpq hrrt"

application:
  security:
    jwt:
      secret-key: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
